name: Playwright

on: 
  workflow_dispatch:
    inputs:
      data-filename:
        description: 'Data file name'
        required: true
        default: 'commands.json'

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
      
      - name: Install dependencies
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        run: DATE_FILENAME=${{ inputs.data-filename }} npx playwright test

      - name: Get current time
        uses: josStorer/get-current-time@v2.0.1
        id: current-time
        with:
          format: YYYYMMDDHHmmss
          utcOffset: "+09:00"
          
      - name: Upload logs as artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.current-time.outputs.formattedTime }}-playwright-report
          path: playwright-report/
